#!/bin/bash
#
# multinotmuch, a simple wrapper for multi and separate notmuch accounts
# Copyright (C) 2013  Sebastien Badia <seb@sebian.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

show_help() {
  cat <<-EOF
Usage:
  $(basename $0) [OPTION]

  -a [enovance|ldn|sebian]  Run notmuch using this account
  -c command                Notmuch command
  -h                        Show this help

EOF
}

while getopts "a:c:h" opt; do
  case $opt in
    a) ACCOUNT=$OPTARG
      ;;
    c) COMMAND=$OPTARG
      ;;
    h) show_help
      exit 2
      ;;
    *) echo "Bad params, please see $(basename $0) -h"
      exit 1
      ;;
  esac
done

if [ -z $ACCOUNT ]; then
  echo 'Account name is required !'
  exit 1
elif [ ! "$ACCOUNT" = "enovance" -a ! "$ACCOUNT" = "ldn" -a ! "$ACCOUNT" = "sebian" ]; then
  echo "$ACCOUNT unknow !"
  exit 1
else
  NOTMUCH_CONFIG=~/crypt/mutt/notmuch-$ACCOUNT notmuch $COMMAND
fi
