#!/bin/bash
# Author:: Sebastien Badia (<seb@sebian.fr>)
# Date:: jeudi 15 septembre 2011, 19:59:18 (UTC+0200)
# Petit script pour configurer le dual screen en
# fonction de la config.
MODE=$1
VERBOSE="1"

usage() {
cat <<-EOF
Usage:
start [OPTION]
  -2h: Two display with hdmi output
  -2v: Two display with vga output
  -lh: Laptop screen disable hdmi
  -lv: Laptop screen disable vga
  -l: Laptop screen
  -h: This help

https://github.com/sbadia/grimtools/blob/master/start
EOF
}

laptop_x() {
  xrandr --output LVDS1 --mode 1366x768 --primary
}

xrand() {
  local display="$1"
  xrandr --output $display --noprimary --mode 1680x1050
  xrandr --output $display --auto --left-of LVDS1
}

xbattbar() {
  #rel "xbattbar" "-a -c -t 2"
  #rel "volumeicon"
  #rel "xfce4-clipman"
  [[ -x /usr/bin/nitrogen ]] && sleep 2;/usr/bin/nitrogen --restore
  exit 0
}

rel() {
  local name="$1"
  local opts="$2"
  [[ -x /usr/bin/$name ]] && /usr/bin/killall -HUP $name -q
  [[ -x /usr/bin/$name ]] && /usr/bin/$name $opts 2> /dev/null 2>&1 &
  #[[ -x /usr/bin/$name ]] && /usr/bin/$name $opts 2> /dev/null &
}

if [ -f ~/.config/awesome/rc.lua ]; then
  if [ "$MODE" == "2h" ]; then
    if [ "$VERBOSE" == "1" ]; then
      echo "--> HDMI Screen + Laptop"
    fi
    #sed -e 's/^local\ conf\ =\ 1/local conf = 2/' -i ~/.config/awesome/rc.lua
    laptop_x
    xrand "HDMI3"
    xbattbar
  elif [ "$MODE" == "2v" ]; then
    if [ "$VERBOSE" == "1" ]; then
      echo "--> VGA Screen + Laptop"
    fi
    #sed -e 's/^local\ conf\ =\ 1/local conf = 2/' -i ~/.config/awesome/rc.lua
    laptop_x
    xrand "VGA1"
    xbattbar
  elif [ "$MODE" == "lh" ]; then
      if [ "$VERBOSE" == "1" ]; then
        echo "--> Disable HDMI screen"
      fi
      xrandr --output HDMI3 --off
      #sed -e 's/^local\ conf\ =\ 2/local conf = 1/' -i ~/.config/awesome/rc.lua
      laptop_x
      xbattbar
  elif [ "$MODE" == "lv" ]; then
      if [ "$VERBOSE" == "1" ]; then
        echo "--> Disable VGA screen"
      fi
      xrandr --output VGA1 --off
      #sed -e 's/^local\ conf\ =\ 2/local conf = 1/' -i ~/.config/awesome/rc.lua
      laptop_x
      xbattbar
  elif [ "$MODE" == "l" ]; then
      #sed -e 's/^local\ conf\ =\ 2/local conf = 1/' -i ~/.config/awesome/rc.lua
      laptop_x
      xbattbar
  else
    usage
  fi
else
  echo "No awesome config..."
  exit 1
fi
