#!/bin/bash
#
# start, a little xrand wrapper
# Copyright (C) 2011-2014  Sebastien Badia <seb@sebian.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#set -x

VERBOSE="1"
LOCAL_DISPLAY="LVDS1"
POS='left-of'
DUAL='local'

usage() {
cat <<-EOF
Usage:
  $(basename $0) [OPTION]

  -H  Dual screen with HDMI
  -V  Dual screen with VGA
  -p  Position (in case-of dual-screen) [left-of|above|bellow|right-of|same-as]
  -h: This help

  https://github.com/sbadia/grimtools/blob/master/start
EOF
}

laptop_x() {
  xrandr --output $LOCAL_DISPLAY --mode 1366x768 --primary
}

xrand() {
  local display="$1"
  local position="$2"
  xrandr --output $display --noprimary --mode 1680x1050
  xrandr --output $display --auto --${position} $LOCAL_DISPLAY
}

xbattbar() {
  #rel "xbattbar" "-a -c -t 2"
  [[ -x /usr/bin/nitrogen ]] && sleep 2;/usr/bin/nitrogen --restore
  exit 0
}

rel() {
  local name="$1"
  local opts="$2"
  [[ -x /usr/bin/$name ]] && /usr/bin/killall -HUP $name -q
  [[ -x /usr/bin/$name ]] && /usr/bin/$name $opts 2> /dev/null 2>&1 &
}

while getopts "hVHp:" opt; do
  case $opt in
    h)
      usage
      exit 0
      ;;
    V)
      DUAL='VGA1'
      ;;
    H)
      DUAL='HDMI3'
      ;;
    p)
      POS=$OPTARG
      ;;
    *)
      exit 1
      ;;
  esac
done

if [ -f ~/.config/awesome/rc.lua ]; then
  if [ "$DUAL" == "local" ]; then
    laptop_x
    # disable the HDMI or VGA screen connected
    disable=$(xrandr|awk '/^(H|V).*\sconnected/ {print $1}')
    xrandr --output $disable --off
    xbattbar
  else
    laptop_x
    xrand $DUAL $POS
    xbattbar
  fi
else
  echo "No awesome config..."
  exit 1
fi
