#!/bin/bash
#
# start, a little xrand wrapper
# Copyright (C) 2011-2014  Sebastien Badia <seb@sebian.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#set -x

VERBOSE="1"
LOCAL_DISPLAY="LVDS1"
POS='left-of'
DUAL='local'

usage() {
cat <<-EOF
Usage:
  $(basename $0) [OPTION]

  -H  Dual screen with HDMI
  -V  Dual screen with VGA
  -p  Position (in case-of dual-screen) [left-of|above|bellow|right-of|same-as]
  -h: This help

  https://github.com/sbadia/grimtools/blob/master/start
EOF
}

laptop_x() {
  xrandr --output $LOCAL_DISPLAY --mode 1366x768 --primary
}

xrand() {
  local display="$1"
  local position="$2"
  xrandr --output $display --noprimary --mode 1680x1050
  xrandr --output $display --auto --${position} $LOCAL_DISPLAY
}

xbattbar() {
  #rel "xbattbar" "-a -c -t 2"
  [[ -x /usr/bin/nitrogen ]] && sleep 2;/usr/bin/nitrogen --restore
  exit 0
}

rel() {
  local name="$1"
  local opts="$2"
  [[ -x /usr/bin/$name ]] && /usr/bin/killall -HUP $name -q
  [[ -x /usr/bin/$name ]] && /usr/bin/$name $opts 2> /dev/null 2>&1 &
}

log() {
  if [ "$VERBOSE" == "1" ]; then
    local level=$1
    local msg=$2
    c=''
    case $level in
      'err')
        c='\033[31m[E]\033[39m '
        ;;
      'info')
        c='\033[32m[I]\033[39m '
        ;;
      *)
        echo "Unknown log level ($level)"
        exit 1
    esac
    echo -e "${c}${msg}"
  fi
}

check_params() {
  if ! [[ "$DUAL" = "VGA1" || "$DUAL" = "HDMI3" || "$DUAL" = "local" ]]; then
    log err "Unknown dual-screen mode ($DUAL)"
    exit 1
  fi
  if ! [[ "$POS" = "left-of" || "$POS" = "above" || "$POS" = "bellow" || "$POS" = "right-of" || "$POS" = "same-as" ]]; then
    log err "Unknown screen position ($POS)"
    exit 1
  fi
}

while getopts "hVHp:" opt; do
  case $opt in
    h)
      usage
      exit 0
      ;;
    V)
      DUAL='VGA1'
      ;;
    H)
      DUAL='HDMI3'
      ;;
    p)
      POS=$OPTARG
      ;;
    *)
      log err "Bad parameter, please run $(basename $0) -h"
      exit 1
      ;;
  esac
done

if [ -f ~/.config/awesome/rc.lua ]; then
  check_params
  if [ "$DUAL" == "local" ]; then
    laptop_x
    # disable the HDMI or VGA screen connected
    disable=$(xrandr|awk '/^(H|V).*\sconnected/ {print $1}')
    xrandr --output $disable --off
    log info "Screen $disable off; $LOCAL_DISPLAY only"
    xbattbar
  else
    laptop_x
    xrand $DUAL $POS
    log info "Screen $DUAL on ($POS of $LOCAL_DISPLAY)"
    xbattbar
  fi
else
  log err "No awesome config..."
  exit 1
fi
