#!/usr/bin/ruby -w
# Author:: Sebastien Badia (<seb@sebian.fr>)
branch = ARGV[0]
if (File.directory?(".git") == true) then
  system("git branch #{branch}")
  system("git checkout #{branch}")
else
  puts "Not in a GIT repo..."
  exit 1
end
