#!/usr/bin/ruby -w
# Author:: Sebastien Badia (<seb@sebian.fr>)
# Date:: Fri Jul 01 13:57:40 +0200 2011
# Little script for update all repo

# Update /home/sbadia/dev directory
# $ repull
#
# Update /home/sbadia/dev/NOTACTIVE directory
# $ repull ~/dev/NOTACTIVE
#
# ...
require 'pp'
require '~/bin/peach'

dev = ARGV[0]
verbose = false

extinction = Proc.new{
  puts "Received extinction request..."
}
%w{INT TERM}.each do |signal|
  Signal.trap( signal ) do
    extinction.call
    exit(1)
  end
end

if (defined? dev)&&(dev == nil)
  dev = "/home/sbadia/dev"
end

puts "[Update #{dev} repo]"
repo = Dir.entries(dev)
Dir.chdir(dev)
if (verbose == true) then
  puts "Répertoire "+Dir.pwd
end
#repo.to_a.peach(repo.length) do |g|
repo.each do |g|
  if (File.directory?(g) == true) then
    Dir.chdir(g)
      if (File.directory?(".svn") == true) then
        if (verbose == true) then
	  puts "Versioning SVN"
	end
        puts "### Update "+g
	system("svn update")
      elsif (File.directory?(".git") == true) then
	if (verbose == true) then
	  puts "Versioning GIT"
	end
      puts "*** Update "+g
      system("git pull")
     elsif (File.directory?(".hg") == true) then
	if (verbose == true) then
	  puts "Versioning Mercurial"
	end
	puts "%%% Update "+g
	system("hg pull")
     else
	if (verbose == true) then
	  puts "Not supported yet"
       end
     end
     Dir.chdir(dev)
  else
    if (verbose == true) then
      puts "File "+g
    end
  end
end
if (verbose == true) then
	puts "Répertoire "+Dir.pwd
end
puts "[Update #{dev} Done !]"
