#!/bin/sh

# Clear all clipboards
xsel -p -c
xsel -s -c
xsel -b -c

# Stop all VPN
sudo systemctl stop openvpn.service
#sudo killall openconnect # Cloudwatt

sync
i3lock -i /home/sbadia/wallpaper/degradevert.png -e -d & sudo pm-suspend
