#!/bin/bash
# Author:: Sebastien Badia (<seb@sebian.fr>)
# Date:: jeudi 15 septembre 2011, 19:55:18 (UTC+0200)
# Petit script pour loader les clées ssh de son .ssh/

/usr/bin/ssh-add -l
/usr/bin/ssh-add -D
declare -a cle
cle=( `ls ~/.ssh/ |grep -v '\(pub\|know\|conf\|puppetplay\)'` )
cd ~/.ssh/
pwd
for i in ${cle[*]};
  do echo "Cle "$i;
    /usr/bin/ssh-add $i < /usr/bin/ssh-askpass
    echo "naughty.notify({title = 'Sshlo: Load ssh keys', text = '$i Loaded', timeout = 5})" | /usr/bin/awesome-client
done
cd ~
pwd
/usr/bin/ssh-add -l
echo "naughty.notify({title = 'Sshlo: Done', text = 'All user key loaded', timeout = 8})" | /usr/bin/awesome-client
