#!/bin/bash
# Author:: Sebastien Badia (<seb@sebian.fr>)
# Date:: jeudi 15 septembre 2011, 19:59:18 (UTC+0200)
# Petit script pour configurer le dual screen en
# fonction de la config.

MODE=$1
TYPE=$2
VERBOSE="1"

#echo -e "Usage:\nstart -[2h|2v|l[h|v]]\n\t-2h: Two display with hdmi output\n\t-2v: Two display with vga output\n\t-l: Laptop screen\n\t-lh: Laptop screen disable hdmi\n\t-lv: Laptop screen disable vga"
usage()
{
cat <<-EOF
Usage:
start [OPTION]
  -2h: Two display with hdmi output
  -2v: Two display with vga output
  -lh: Laptop screen disable hdmi
  -lv: Laptop screen disable vga
  -l: Laptop screen
  -h: This help

https://github.com/sbadia/utils-gh/blob/master/utils/start
EOF
}

laptop()
{
  sed -e 's/^local\ conf\ =\ 2/local conf = 1/' -i ~/.config/awesome/rc.lua
  echo "--> Laptop screen"
  xrandr --output eDP1 --mode 1366x768 --primary
}

xbattbar() {
  reload "xbattbar -c -t"
  reload "volumeicon"
  [[ -x /usr/bin/nitrogen ]] && /usr/bin/nitrogen --restore
}

reload() {
  local name="$1"
  [[ -x /usr/bin/$name ]] && /usr/bin/killall -HUP $name -q
  [[ -x /usr/bin/$name ]] && /usr/bin/$name 2 > /dev/null 2>&1 &
}

if [ -f ~/.config/awesome/rc.lua ]; then
  if [ "$MODE" == "2h" ]; then
    if [ "$VERBOSE" == "1" ]; then
      echo "--> HDMI Screen + Laptop"
    fi
    sed -e 's/^local\ conf\ =\ 1/local conf = 2/' -i ~/.config/awesome/rc.lua
    xrandr --output HDMI1 --noprimary --mode 1680x1050
    xrandr --output HDMI1 --auto --left-of eDP1
    xbattbar
  elif [ "$MODE" == "2v" ]; then
    if [ "$VERBOSE" == "1" ]; then
      echo "--> VGA Screen + Laptop"
    fi
    sed -e 's/^local\ conf\ =\ 1/local conf = 2/' -i ~/.config/awesome/rc.lua
    xrandr --output VGA1 --noprimary --mode 1680x1050
    xrandr --output VGA1 --auto --left-of eDP1
    xbattbar
  elif [ "$MODE" == "lh" ]; then
      if [ "$VERBOSE" == "1" ]; then
        echo "--> Disable HDMI screen"
      fi
      xrandr --output HDMI1 --off
      laptop
      xbattbar
  elif [ "$MODE" == "lv" ]; then
      if [ "$VERBOSE" == "1" ]; then
        echo "--> Disable VGA screen"
      fi
      xrandr --output VGA1 --off
      laptop
      xbattbar
  elif [ "$MODE" == "l" ]; then
      laptop
      xbattbar
  else
    usage
  fi
else
  echo "No awesome config..."
  exit 1
fi
