#!/bin/sh

LOCKFILE=/tmp/sync-mail.lock
[ -f $LOCKFILE ] && exit 0
trap "{ rm -f $LOCKFILE ; exit 0; }" EXIT
echo "$$" > $LOCKFILE

/bin/ping -c 1 zimbra.enovance.com >/dev/null 2>&1 || exit 0
/usr/bin/offlineimap -a eNovance -u TTYUI
